import React, { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import axios from "axios";
import "./ReportView.css";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000/api";

interface Report {
  id: number;
  product_id: number;
  transparency_score: number;
  report_data: any;
  generated_at: string;
  product_name: string;
  category: string;
}

const ReportView: React.FC = () => {
  const { productId } = useParams();
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReport();
  }, [productId]);

  const fetchReport = async () => {
    try {
      const response = await axios.get(`${API_URL}/reports/${productId}`);
      setReport(response.data);
    } catch (error) {
      console.error("Error fetching report:", error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return <div className="loading">Loading report...</div>;
  }

  if (!report) {
    return (
      <div className="error-state">
        <h2>Report not found</h2>
        <Link to="/" className="btn-primary">
          Back to Dashboard
        </Link>
      </div>
    );
  }

  const reportData =
    typeof report.report_data === "string"
      ? JSON.parse(report.report_data)
      : report.report_data;

  return (
    <div className="report-view">
      <div className="report-header no-print">
        <Link to="/" className="btn-secondary">
          ← Back to Dashboard
        </Link>
        <button onClick={() => window.print()} className="btn-primary">
          Download PDF
        </button>
      </div>

      <div className="report-content">
        <div className="report-title">
          <h1>Product Transparency Report</h1>
          <p className="report-date">
            Generated: {new Date(report.generated_at).toLocaleString()}
          </p>
        </div>

        <div className="report-section">
          <h2>Product Information</h2>
          <div className="info-grid">
            <div className="info-item">
              <span className="label">Product Name:</span>
              <span className="value">{report.product_name}</span>
            </div>
            <div className="info-item">
              <span className="label">Category:</span>
              <span className="value">
                {report.category || "Not specified"}
              </span>
            </div>
          </div>
        </div>

        <div className="report-section">
          <h2>Transparency Score</h2>
          <div className="score-display">
            <div className="score-circle">
              <span className="score-value">{report.transparency_score}</span>
              <span className="score-label">/ 100</span>
            </div>
            <p className="score-description">
              {report.transparency_score >= 80 && "Excellent transparency"}
              {report.transparency_score >= 60 &&
                report.transparency_score < 80 &&
                "Good transparency"}
              {report.transparency_score >= 40 &&
                report.transparency_score < 60 &&
                "Moderate transparency"}
              {report.transparency_score < 40 && "Needs improvement"}
            </p>
          </div>
        </div>

        <div className="report-section">
          <h2>Detailed Responses</h2>
          {Object.entries(reportData.categories || {}).map(
            ([category, items]: [string, any]) => (
              <div key={category} className="category-section">
                <h3>{category}</h3>
                <div className="responses-list">
                  {items.map((item: any, index: number) => (
                    <div key={index} className="response-item">
                      <p className="question">{item.question}</p>
                      <p className="answer">{item.answer || "Not answered"}</p>
                    </div>
                  ))}
                </div>
              </div>
            )
          )}
        </div>

        <div className="report-footer">
          <p>This report was generated by Product Transparency Platform</p>
          <p>Committed to Health, Wisdom, and Virtue</p>
        </div>
      </div>
    </div>
  );
};

export default ReportView;
